develop #630 test - Then An exception was thrown [Jenkins]Skip to contentJenkinslog inDashboarddevelop#630Test ResultsTest Results(root)Scenario: Creating Users Under Account That Has Limited Child UsersThen An exception was thrownBack to ProjectStatusChangesConsole OutputView as plain textView Build InformationHistoryPolling LogGit Build DataTest ResultPrevious BuildNext BuildPassedScenario: Creating Users Under Account That Has Limited Child Users.Then An exception was thrown (from org.eclipse.kapua.integration.service.account.RunAccountServiceI9nTest)Took 0 ms.REST APIJenkins 2.263.2
